# Generated by Django 5.0.6 on 2026-05-23 23:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('filename', models.CharField(max_length=255, verbose_name='نام فایل')),
                ('file_path', models.CharField(max_length=500, verbose_name='مسیر فایل')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='حجم فایل (بایت)')),
                ('status', models.CharField(choices=[('success', 'موفق'), ('failed', 'ناموفق'), ('restored', 'بازیابی شده')], default='success', max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان بازیابی')),
                ('checksum', models.CharField(blank=True, max_length=64, verbose_name='چکسام SHA256')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_created', to=settings.AUTH_USER_MODEL, verbose_name='توسط')),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_restored', to=settings.AUTH_USER_MODEL, verbose_name='بازیابی توسط')),
            ],
            options={
                'verbose_name': 'بکاپ',
                'verbose_name_plural': 'بکاپ\u200cها',
                'db_table': 'backups_record',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='backups_rec_created_35292a_idx'), models.Index(fields=['status'], name='backups_rec_status_a3a2bf_idx')],
            },
        ),
    ]
