# Generated by Django 5.0.6 on 2026-05-23 23:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('alert_type', models.CharField(choices=[('low_stock', 'موجودی کم'), ('out_of_stock', 'ناموجود'), ('expiry_warning', 'هشدار انقضا'), ('expired', 'منقضی شده'), ('customer_debt', 'بدهی مشتری'), ('supplier_debt', 'بدهی تامین\u200cکننده'), ('backup', 'یادآوری بکاپ')], max_length=30, verbose_name='نوع هشدار')),
                ('severity', models.CharField(choices=[('info', 'اطلاعات'), ('warning', 'هشدار'), ('critical', 'بحرانی')], default='warning', max_length=20, verbose_name='شدت')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='پیام')),
                ('reference_id', models.CharField(blank=True, max_length=100, verbose_name='شناسه مرجع')),
                ('reference_url', models.CharField(blank=True, max_length=300, verbose_name='لینک مرجع')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('is_dismissed', models.BooleanField(default=False, verbose_name='رد شده')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان خواندن')),
                ('read_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_alerts', to=settings.AUTH_USER_MODEL, verbose_name='خوانده شده توسط')),
            ],
            options={
                'verbose_name': 'هشدار',
                'verbose_name_plural': 'هشدارها',
                'db_table': 'alerts_alert',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['alert_type'], name='alerts_aler_alert_t_e287ad_idx'), models.Index(fields=['severity'], name='alerts_aler_severit_202179_idx'), models.Index(fields=['is_read'], name='alerts_aler_is_read_ba5dfd_idx'), models.Index(fields=['is_dismissed'], name='alerts_aler_is_dism_e05d15_idx'), models.Index(fields=['-created_at'], name='alerts_aler_created_574618_idx')],
            },
        ),
    ]
