# Generated by Django 5.0.6 on 2026-05-23 22:04

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='شماره فاکتور')),
                ('invoice_date', models.DateField(verbose_name='تاریخ فاکتور')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='مجموع قبل از تخفیف')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='تخفیف کل')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='مبلغ کل')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='مبلغ پرداخت شده')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='مبلغ باقی\u200cمانده')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='قیمت تمام شده کل (FIFO)')),
                ('previous_debt', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='بدهی قبلی مشتری')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('confirmed', 'تایید شده'), ('partial', 'پرداخت جزئی'), ('paid', 'پرداخت کامل'), ('cancelled', 'لغو شده')], default='confirmed', max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customers.customer', verbose_name='مشتری')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='warehouse.warehouse', verbose_name='انبار')),
            ],
            options={
                'verbose_name': 'فاکتور فروش',
                'verbose_name_plural': 'فاکتورهای فروش',
                'db_table': 'sales_invoice',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='مقدار')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت فروش فی واحد')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='تخفیف %')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='مبلغ تخفیف')),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='مجموع ردیف')),
                ('unit_cost_fifo', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='قیمت خرید FIFO فی واحد')),
                ('total_cost_fifo', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='قیمت تمام شده FIFO')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.invoice', verbose_name='فاکتور')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='inventory.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'ردیف فاکتور',
                'verbose_name_plural': 'ردیف\u200cهای فاکتور',
                'db_table': 'sales_invoice_item',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='مبلغ')),
                ('payment_method', models.CharField(choices=[('cash', 'نقد'), ('credit', 'نسیه'), ('bank', 'بانک'), ('mobile', 'موبایل پول')], default='cash', max_length=20, verbose_name='روش پرداخت')),
                ('payment_date', models.DateField(verbose_name='تاریخ پرداخت')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.invoice', verbose_name='فاکتور')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='دریافت\u200cکننده')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'db_table': 'sales_payment',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='sales_invoi_invoice_51f3c9_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer', '-invoice_date'], name='sales_invoi_custome_311f14_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='sales_invoi_status_4e3758_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['-invoice_date'], name='sales_invoi_invoice_2b2015_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['invoice'], name='sales_invoi_invoice_210133_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['product'], name='sales_invoi_product_16a611_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice', '-payment_date'], name='sales_payme_invoice_bb7271_idx'),
        ),
    ]
