# Generated by Django 5.0.6 on 2026-06-16 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banker', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='banker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_invoices', to='banker.banker', verbose_name='صراف'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('AFN', 'افغانی'), ('USD', 'دالر')], default='AFN', max_length=3, verbose_name='واحد پول'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقد'), ('credit', 'نسیه'), ('bank', 'بانک'), ('mobile', 'موبایل پول'), ('saraf', 'صراف')], default='cash', max_length=20, verbose_name='روش پرداخت'),
        ),
    ]
