# Generated by Django 5.0.6 on 2026-06-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_invoice_banker_invoice_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقد'), ('credit', 'نسیه'), ('bank', 'بانک'), ('mobile', 'موبایل پول'), ('saraf', 'صراف'), ('dakkan', 'دخل دکان')], default='cash', max_length=20, verbose_name='روش پرداخت'),
        ),
    ]
