# Generated by Django 5.0.6 on 2026-06-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقد'), ('credit', 'نسیه'), ('saraf', 'صراف'), ('dakkan', 'دخل دکان')], default='cash', max_length=20, verbose_name='روش پرداخت'),
        ),
    ]
