# Generated by Django 5.0.6 on 2026-05-23 22:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('name', models.CharField(max_length=200, verbose_name='نام مشتری')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('phone2', models.CharField(blank=True, max_length=20, verbose_name='تلفن دوم')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='حد اعتبار')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='بدهی اولیه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
                'db_table': 'customers_customer',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='customers_c_name_f018e2_idx'), models.Index(fields=['phone'], name='customers_c_phone_8493fa_idx'), models.Index(fields=['is_active'], name='customers_c_is_acti_91d305_idx')],
            },
        ),
    ]
