# Generated by Django 5.0.6 on 2026-05-23 22:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='مبلغ')),
                ('payment_method', models.CharField(choices=[('cash', 'نقد'), ('bank', 'بانک'), ('mobile', 'موبایل پول')], default='cash', max_length=20, verbose_name='روش پرداخت')),
                ('payment_date', models.DateField(verbose_name='تاریخ پرداخت')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_payments', to='customers.customer', verbose_name='مشتری')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='دریافت\u200cکننده')),
            ],
            options={
                'verbose_name': 'پرداخت مستقیم مشتری',
                'verbose_name_plural': 'پرداخت\u200cهای مستقیم مشتریان',
                'db_table': 'customers_payment',
                'ordering': ['-payment_date', '-created_at'],
                'indexes': [models.Index(fields=['customer', '-payment_date'], name='customers_p_custome_d52b95_idx')],
            },
        ),
    ]
