# Generated by Django 5.0.6 on 2026-05-23 22:29

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customerpayment'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('tx_type', models.CharField(choices=[('opening_debt', 'بدهی اولیه'), ('opening_advance', 'پیش\u200cپرداخت اولیه'), ('invoice', 'فاکتور فروش'), ('payment', 'دریافت وجه'), ('advance_add', 'افزایش پیش\u200cپرداخت'), ('advance_use', 'استفاده از پیش\u200cپرداخت'), ('advance_refund', 'برگشت پیش\u200cپرداخت'), ('debt_write_off', 'بخشودگی بدهی'), ('reversal', 'برگشت تراکنش'), ('adjustment', 'تعدیل')], max_length=30, verbose_name='نوع تراکنش')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='مبلغ')),
                ('debt_before', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('debt_after', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('advance_before', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('advance_after', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('is_reversed', models.BooleanField(default=False, verbose_name='برگشت شده')),
                ('payment_method', models.CharField(blank=True, max_length=20, verbose_name='روش پرداخت')),
                ('transaction_date', models.DateField(verbose_name='تاریخ تراکنش')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
            ],
            options={
                'verbose_name': 'تراکنش مشتری',
                'verbose_name_plural': 'تراکنش\u200cهای مشتری',
                'db_table': 'customers_transaction',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='customerpayment',
            options={'ordering': ['-payment_date', '-created_at'], 'verbose_name': 'پرداخت مستقیم', 'verbose_name_plural': 'پرداخت\u200cهای مستقیم'},
        ),
        migrations.RemoveIndex(
            model_name='customerpayment',
            name='customers_p_custome_d52b95_idx',
        ),
        migrations.AddField(
            model_name='customer',
            name='advance_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='موجودی پیش\u200cپرداخت'),
        ),
        migrations.AddField(
            model_name='customer',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='کد مشتری'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_transaction_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ آخرین تراکنش'),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='مجموع بدهی'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='بدهی اولیه'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['code'], name='customers_c_code_4fafda_idx'),
        ),
        migrations.AddField(
            model_name='customertransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='توسط'),
        ),
        migrations.AddField(
            model_name='customertransaction',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='customers.customer', verbose_name='مشتری'),
        ),
        migrations.AddField(
            model_name='customertransaction',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_transactions', to='sales.invoice', verbose_name='فاکتور'),
        ),
        migrations.AddField(
            model_name='customertransaction',
            name='reversed_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal_of', to='customers.customertransaction', verbose_name='برگشت داده شده توسط'),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_record', to='customers.customertransaction', verbose_name='تراکنش'),
        ),
        migrations.AddIndex(
            model_name='customertransaction',
            index=models.Index(fields=['customer', '-transaction_date'], name='customers_t_custome_f24a27_idx'),
        ),
        migrations.AddIndex(
            model_name='customertransaction',
            index=models.Index(fields=['tx_type'], name='customers_t_tx_type_cf9531_idx'),
        ),
        migrations.AddIndex(
            model_name='customertransaction',
            index=models.Index(fields=['is_reversed'], name='customers_t_is_reve_2f19a1_idx'),
        ),
        migrations.AddIndex(
            model_name='customertransaction',
            index=models.Index(fields=['invoice'], name='customers_t_invoice_1153a9_idx'),
        ),
    ]
