# Generated by Django 5.0.6 on 2026-06-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customertransaction_alter_customerpayment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقد'), ('bank', 'بانک'), ('mobile', 'موبایل پول'), ('saraf', 'صراف')], default='cash', max_length=20, verbose_name='روش پرداخت'),
        ),
    ]
