# Generated by Django 5.0.6 on 2026-06-16 07:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customerpayment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='advance_balance_usd',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='موجودی پیش\u200cپرداخت (دالر)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_debt_usd',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16, verbose_name='مجموع بدهی (دالر)'),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='currency',
            field=models.CharField(choices=[('AFN', 'افغانی'), ('USD', 'دالر')], default='AFN', max_length=3, verbose_name='ارز'),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=12, verbose_name='نرخ تبدیل'),
        ),
        migrations.AddField(
            model_name='customertransaction',
            name='advance_after_usd',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='customertransaction',
            name='advance_before_usd',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='customertransaction',
            name='amount_afn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='معادل افغانی'),
        ),
        migrations.AddField(
            model_name='customertransaction',
            name='currency',
            field=models.CharField(choices=[('AFN', 'افغانی'), ('USD', 'دالر')], default='AFN', max_length=3, verbose_name='ارز'),
        ),
        migrations.AddField(
            model_name='customertransaction',
            name='debt_after_usd',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='customertransaction',
            name='debt_before_usd',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='customertransaction',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=12, verbose_name='نرخ تبدیل (۱ USD = ؟ AFN)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='advance_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='موجودی پیش\u200cپرداخت (افغانی)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='مجموع بدهی (افغانی)'),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=14, verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='customertransaction',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=16, verbose_name='مبلغ'),
        ),
    ]
