# Generated by Django 5.0.6 on 2026-06-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_advance_balance_usd_customer_total_debt_usd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقد'), ('saraf', 'صراف')], default='cash', max_length=20, verbose_name='روش پرداخت'),
        ),
    ]
