# Generated by Django 5.0.6 on 2026-06-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_customerpayment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_limit_usd',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='حد اعتبار (دالر)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='opening_balance_usd',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16, verbose_name='بدهی اولیه (دالر)'),
        ),
    ]
