# Generated by Django 5.0.6 on 2026-06-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customer_credit_limit_usd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقد'), ('saraf', 'صراف'), ('dakkan', 'دخل دکان')], default='cash', max_length=20, verbose_name='روش پرداخت'),
        ),
    ]
