# Generated by Django 5.0.6 on 2026-05-23 22:57

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='کد ارز')),
                ('name', models.CharField(max_length=100, verbose_name='نام ارز')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='نام انگلیسی')),
                ('symbol', models.CharField(max_length=10, verbose_name='نماد')),
                ('is_base', models.BooleanField(default=False, verbose_name='ارز پایه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('decimal_places', models.PositiveSmallIntegerField(default=2, verbose_name='اعشار')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'ارز',
                'verbose_name_plural': 'ارزها',
                'db_table': 'currency_currency',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('rate_date', models.DateField(verbose_name='تاریخ')),
                ('rate_to_afn', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='نرخ به افغانی')),
                ('buy_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='نرخ خرید')),
                ('sell_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='نرخ فروش')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='یادداشت')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='currency.currency', verbose_name='ارز')),
            ],
            options={
                'verbose_name': 'نرخ ارز',
                'verbose_name_plural': 'نرخ\u200cهای ارز',
                'db_table': 'currency_exchange_rate',
                'ordering': ['-rate_date', 'currency'],
                'indexes': [models.Index(fields=['currency', '-rate_date'], name='currency_ex_currenc_23dd80_idx'), models.Index(fields=['-rate_date'], name='currency_ex_rate_da_63e976_idx')],
                'unique_together': {('currency', 'rate_date')},
            },
        ),
    ]
