# Generated by Django 5.0.6 on 2026-06-25 10:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='shopincometransfer',
            new_name='capital_sho_transfe_ee3818_idx',
            old_name='capital_sit_date_idx',
        ),
        migrations.RenameIndex(
            model_name='shopincometransfer',
            new_name='capital_sho_banker__a431a4_idx',
            old_name='capital_sit_banker_idx',
        ),
        migrations.RenameIndex(
            model_name='shopincometransfer',
            new_name='capital_sho_currenc_d4abdb_idx',
            old_name='capital_sit_currency_idx',
        ),
        migrations.AlterField(
            model_name='shopincometransfer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='shopincometransfer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف'),
        ),
        migrations.AlterField(
            model_name='shopincometransfer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shopincometransfer',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='حذف شده'),
        ),
        migrations.AlterField(
            model_name='shopincometransfer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش'),
        ),
    ]
