# Generated by Django 5.0.6 on 2026-06-25 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banker', '0002_banker_balance_eur_banker_balance_irr_and_more'),
        ('capital', '0002_rename_capital_sit_date_idx_capital_sho_transfe_ee3818_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopincometransfer',
            name='banker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shop_income_transfers', to='banker.banker', verbose_name='صراف'),
        ),
    ]
