# Generated by Django 5.0.6 on 2026-06-25 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banker', '0002_banker_balance_eur_banker_balance_irr_and_more'),
        ('capital', '0003_alter_shopincometransfer_banker'),
        ('purchases', '0007_alter_purchaseinvoice_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shopincometransfer',
            name='purchase_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_income_transfers', to='purchases.purchaseinvoice', verbose_name='فاکتور خرید'),
        ),
        migrations.AddIndex(
            model_name='shopincometransfer',
            index=models.Index(fields=['purchase_invoice'], name='capital_sho_purchas_fef98d_idx'),
        ),
    ]
