# Generated by Django 5.0.6 on 2026-05-23 23:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='نام کاربری')),
                ('action', models.CharField(choices=[('create', 'ایجاد'), ('update', 'ویرایش'), ('delete', 'حذف'), ('login', 'ورود'), ('logout', 'خروج'), ('view', 'مشاهده'), ('print', 'پرینت'), ('export', 'خروجی'), ('payment', 'پرداخت'), ('backup', 'بکاپ'), ('restore', 'بازیابی'), ('adjust', 'تعدیل'), ('cancel', 'لغو'), ('approve', 'تایید')], max_length=20, verbose_name='عملیات')),
                ('module', models.CharField(choices=[('inventory', 'موجودی'), ('warehouse', 'انبار'), ('sales', 'فروش'), ('purchases', 'خریداری'), ('customers', 'مشتریان'), ('suppliers', 'تامین\u200cکنندگان'), ('expenses', 'مصارف'), ('currency', 'ارز'), ('sarafi', 'صرافی'), ('accounts', 'حساب\u200cها'), ('backups', 'بکاپ'), ('system', 'سیستم')], max_length=30, verbose_name='ماژول')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='مدل')),
                ('object_id', models.CharField(blank=True, max_length=100, verbose_name='شناسه شیء')),
                ('object_repr', models.CharField(blank=True, max_length=300, verbose_name='نمایش شیء')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='مرورگر')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='اطلاعات اضافی')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لاگ فعالیت',
                'verbose_name_plural': 'لاگ\u200cهای فعالیت',
                'db_table': 'activity_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='activity_lo_created_3aa675_idx'), models.Index(fields=['user', '-created_at'], name='activity_lo_user_id_f9dfaa_idx'), models.Index(fields=['action'], name='activity_lo_action_f14761_idx'), models.Index(fields=['module'], name='activity_lo_module_24c234_idx'), models.Index(fields=['model_name', 'object_id'], name='activity_lo_model_n_7220d1_idx')],
            },
        ),
    ]
