# Generated by Django 5.0.6 on 2026-05-24 00:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('business_name', models.CharField(max_length=200, verbose_name='نام تجاری')),
                ('business_name_en', models.CharField(blank=True, max_length=200, verbose_name='نام انگلیسی')),
                ('phone1', models.CharField(blank=True, max_length=20, verbose_name='تلفن اول')),
                ('phone2', models.CharField(blank=True, max_length=20, verbose_name='تلفن دوم')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('website', models.CharField(blank=True, max_length=200, verbose_name='وبسایت')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='لوگو')),
                ('default_currency', models.CharField(default='AFN', max_length=10, verbose_name='ارز پیش\u200cفرض')),
                ('low_stock_threshold', models.IntegerField(default=10, verbose_name='آستانه موجودی کم (روزها)')),
                ('credit_warning_amount', models.DecimalField(decimal_places=2, default=50000, max_digits=14, verbose_name='مبلغ هشدار بدهی')),
                ('invoice_footer_text', models.TextField(blank=True, default='با تشکر از خرید شما', verbose_name='متن پایین فاکتور')),
                ('invoice_show_fifo_cost', models.BooleanField(default=False, verbose_name='نمایش قیمت تمام شده در فاکتور')),
                ('backup_reminder_days', models.IntegerField(default=1, verbose_name='یادآوری بکاپ (روز)')),
                ('log_retention_days', models.IntegerField(default=90, verbose_name='نگهداری لاگ (روز)')),
                ('designer_credit', models.CharField(default='YangEra', max_length=100, verbose_name='طراح')),
            ],
            options={
                'verbose_name': 'تنظیمات سیستم',
                'verbose_name_plural': 'تنظیمات سیستم',
                'db_table': 'settings_business',
            },
        ),
    ]
