# Generated by Django 5.0.6 on 2026-05-23 21:54

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام انبار')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='موقعیت')),
                ('is_default', models.BooleanField(default=False, verbose_name='انبار پیشفرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
            ],
            options={
                'verbose_name': 'انبار',
                'verbose_name_plural': 'انبارها',
                'db_table': 'warehouse_warehouse',
                'indexes': [models.Index(fields=['is_default'], name='warehouse_w_is_defa_80f80a_idx'), models.Index(fields=['is_active'], name='warehouse_w_is_acti_5ddb4a_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('batch_number', models.CharField(blank=True, max_length=50, verbose_name='شماره بچ')),
                ('initial_quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='مقدار اولیه')),
                ('remaining_quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مقدار باقی\u200cمانده')),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت خرید فی واحد (افغانی)')),
                ('unit_cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت خرید فی واحد (دالر)')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=10, verbose_name='نرخ تبدیل در زمان خرید')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('manufactured_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولید')),
                ('purchase_reference', models.CharField(blank=True, max_length=100, verbose_name='مرجع خرید')),
                ('supplier_name', models.CharField(blank=True, max_length=200, verbose_name='نام تامین\u200cکننده')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='inventory.product', verbose_name='محصول')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_batches', to=settings.AUTH_USER_MODEL, verbose_name='دریافت\u200cکننده')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='warehouse.warehouse', verbose_name='انبار')),
            ],
            options={
                'verbose_name': 'بچ موجودی',
                'verbose_name_plural': 'بچ\u200cهای موجودی',
                'db_table': 'warehouse_stock_batch',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movement_type', models.CharField(choices=[('sale', 'فروش'), ('return', 'برگشت'), ('adjustment', 'تعدیل'), ('transfer', 'انتقال'), ('damage', 'ضایعات')], max_length=20, verbose_name='نوع')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='مقدار')),
                ('unit_cost_at_time', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='قیمت خرید در زمان عملیات')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='مرجع')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='توسط')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='warehouse.stockbatch', verbose_name='بچ')),
            ],
            options={
                'verbose_name': 'حرکت بچ',
                'verbose_name_plural': 'حرکات بچ',
                'db_table': 'warehouse_batch_movement',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['batch', '-created_at'], name='warehouse_b_batch_i_3d2efa_idx'), models.Index(fields=['movement_type'], name='warehouse_b_movemen_95e7a6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['product', 'warehouse', 'created_at'], name='warehouse_s_product_0dea08_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['product', 'remaining_quantity'], name='warehouse_s_product_8462a3_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['expiry_date'], name='warehouse_s_expiry__091c61_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['warehouse', 'remaining_quantity'], name='warehouse_s_warehou_cb166d_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockbatch',
            constraint=models.CheckConstraint(check=models.Q(('remaining_quantity__gte', 0)), name='batch_remaining_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockbatch',
            constraint=models.CheckConstraint(check=models.Q(('unit_cost__gte', 0)), name='batch_cost_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockbatch',
            constraint=models.CheckConstraint(check=models.Q(('remaining_quantity__lte', models.F('initial_quantity'))), name='batch_remaining_lte_initial'),
        ),
    ]
