# Generated by Django 5.0.6 on 2026-06-17 20:35

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_customerpayment_payment_method'),
        ('inventory', '0001_initial'),
        ('sales', '0002_invoice_banker_invoice_currency_and_more'),
        ('warehouse', '0002_alter_warehouse_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='مقدار')),
                ('quantity_delivered', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='مقدار تحویل داده شده')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تحویل'), ('delivered', 'تحویل داده شد'), ('cancelled', 'لغو شد')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('invoice_date', models.DateField(verbose_name='تاریخ فاکتور')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تحویل')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_deliveries', to='customers.customer', verbose_name='مشتری')),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries_made', to=settings.AUTH_USER_MODEL, verbose_name='تحویل\u200cدهنده')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_deliveries', to='sales.invoice', verbose_name='فاکتور')),
                ('invoice_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_delivery', to='sales.invoiceitem', verbose_name='ردیف فاکتور')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_deliveries', to='inventory.product', verbose_name='محصول')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_deliveries', to='warehouse.warehouse', verbose_name='انبار')),
            ],
            options={
                'verbose_name': 'تحویل معلق',
                'verbose_name_plural': 'تحویل\u200cهای معلق',
                'db_table': 'warehouse_pending_delivery',
                'ordering': ['invoice_date', 'created_at'],
                'indexes': [models.Index(fields=['warehouse', 'status'], name='warehouse_p_warehou_1a8c70_idx'), models.Index(fields=['customer', 'status'], name='warehouse_p_custome_6d8b44_idx'), models.Index(fields=['invoice'], name='warehouse_p_invoice_e10f82_idx'), models.Index(fields=['status'], name='warehouse_p_status_55ca89_idx')],
            },
        ),
    ]
