# Generated by Django 5.0.6 on 2026-06-24 21:25

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customer_credit_limit_usd_and_more'),
        ('inventory', '0001_initial'),
        ('sales', '0002_invoice_banker_invoice_currency_and_more'),
        ('warehouse', '0003_pendingdelivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backorder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='مقدار کسری (فروخته شده بدون موجودی)')),
                ('quantity_fulfilled', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='مقدار تامین شده')),
                ('total_cost_fulfilled', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16, verbose_name='هزینه تکمیل شده')),
                ('status', models.CharField(choices=[('open', 'در انتظار موجودی'), ('fulfilled', 'تکمیل شد'), ('cancelled', 'لغو شد')], default='open', max_length=20, verbose_name='وضعیت')),
                ('created_reference', models.CharField(blank=True, max_length=100, verbose_name='مرجع فاکتور')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backorders', to='customers.customer', verbose_name='مشتری')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backorders', to='sales.invoice', verbose_name='فاکتور')),
                ('invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backorders', to='sales.invoiceitem', verbose_name='ردیف فاکتور')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backorders', to='inventory.product', verbose_name='محصول')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backorders', to='warehouse.warehouse', verbose_name='انبار')),
            ],
            options={
                'verbose_name': 'کسری موجودی (سفارش معلق)',
                'verbose_name_plural': 'کسری\u200cهای موجودی (سفارش\u200cهای معلق)',
                'db_table': 'warehouse_backorder',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['product', 'warehouse', 'status'], name='warehouse_b_product_cba330_idx'), models.Index(fields=['status'], name='warehouse_b_status_bb7cfa_idx'), models.Index(fields=['invoice'], name='warehouse_b_invoice_84e8c6_idx')],
            },
        ),
    ]
