# Generated by Django 5.0.6 on 2026-05-23 22:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='کد تامین\u200cکننده')),
                ('name', models.CharField(max_length=200, verbose_name='نام تامین\u200cکننده')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='نام شرکت')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('phone2', models.CharField(blank=True, max_length=20, verbose_name='تلفن دوم')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('total_debt', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='مجموع بدهی ما به تامین\u200cکننده')),
                ('advance_balance', models.DecimalField(decimal_places=2, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='پیش\u200cپرداخت به تامین\u200cکننده')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='بدهی اولیه به تامین\u200cکننده')),
                ('last_transaction_date', models.DateField(blank=True, null=True, verbose_name='تاریخ آخرین تراکنش')),
            ],
            options={
                'verbose_name': 'تامین\u200cکننده',
                'verbose_name_plural': 'تامین\u200cکنندگان',
                'db_table': 'suppliers_supplier',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='suppliers_s_name_6277a9_idx'), models.Index(fields=['code'], name='suppliers_s_code_d1984e_idx'), models.Index(fields=['is_active'], name='suppliers_s_is_acti_a75d30_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupplierTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('tx_type', models.CharField(choices=[('opening_debt', 'بدهی اولیه'), ('opening_advance', 'پیش\u200cپرداخت اولیه'), ('purchase', 'فاکتور خرید'), ('payment', 'پرداخت به تامین\u200cکننده'), ('advance_add', 'پیش\u200cپرداخت به تامین\u200cکننده'), ('advance_use', 'استفاده از پیش\u200cپرداخت'), ('return', 'برگشت خرید'), ('reversal', 'برگشت تراکنش'), ('adjustment', 'تعدیل')], max_length=30, verbose_name='نوع تراکنش')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='مبلغ')),
                ('debt_before', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('debt_after', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('advance_before', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('advance_after', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('is_reversed', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, max_length=20, verbose_name='روش پرداخت')),
                ('transaction_date', models.DateField(verbose_name='تاریخ')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='توسط')),
                ('purchase_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_transactions', to='purchases.purchaseinvoice', verbose_name='فاکتور خرید')),
                ('reversed_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal_of', to='suppliers.suppliertransaction')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='suppliers.supplier', verbose_name='تامین\u200cکننده')),
            ],
            options={
                'verbose_name': 'تراکنش تامین\u200cکننده',
                'verbose_name_plural': 'تراکنش\u200cهای تامین\u200cکنندگان',
                'db_table': 'suppliers_transaction',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='مبلغ')),
                ('payment_method', models.CharField(choices=[('cash', 'نقد'), ('bank', 'بانک'), ('mobile', 'موبایل پول')], default='cash', max_length=20, verbose_name='روش پرداخت')),
                ('payment_date', models.DateField(verbose_name='تاریخ پرداخت')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='پرداخت\u200cکننده')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='suppliers.supplier', verbose_name='تامین\u200cکننده')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_record', to='suppliers.suppliertransaction')),
            ],
            options={
                'verbose_name': 'پرداخت به تامین\u200cکننده',
                'verbose_name_plural': 'پرداخت\u200cهای تامین\u200cکنندگان',
                'db_table': 'suppliers_payment',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='suppliertransaction',
            index=models.Index(fields=['supplier', '-transaction_date'], name='suppliers_t_supplie_a19fdc_idx'),
        ),
        migrations.AddIndex(
            model_name='suppliertransaction',
            index=models.Index(fields=['tx_type'], name='suppliers_t_tx_type_f0368f_idx'),
        ),
        migrations.AddIndex(
            model_name='suppliertransaction',
            index=models.Index(fields=['is_reversed'], name='suppliers_t_is_reve_f44cd1_idx'),
        ),
    ]
