# Generated by Django 5.0.6 on 2026-06-18 10:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_customerpayment_payment_method'),
        ('suppliers', '0002_alter_supplierpayment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='advance_balance_usd',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='پیش\u200cپرداخت ما (دالر)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_account', to='customers.customer', verbose_name='حساب مشتری مرتبط'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='total_debt_usd',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16, verbose_name='بدهی ما (دالر)'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='currency',
            field=models.CharField(choices=[('AFN', 'افغانی'), ('USD', 'دالر')], default='AFN', max_length=3, verbose_name='ارز'),
        ),
        migrations.AddField(
            model_name='suppliertransaction',
            name='advance_after_usd',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='suppliertransaction',
            name='advance_before_usd',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='suppliertransaction',
            name='amount_afn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='معادل افغانی'),
        ),
        migrations.AddField(
            model_name='suppliertransaction',
            name='currency',
            field=models.CharField(choices=[('AFN', 'افغانی'), ('USD', 'دالر')], default='AFN', max_length=3, verbose_name='ارز'),
        ),
        migrations.AddField(
            model_name='suppliertransaction',
            name='debt_after_usd',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='suppliertransaction',
            name='debt_before_usd',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='advance_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='پیش\u200cپرداخت ما (افغانی)'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='total_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='بدهی ما (افغانی)'),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=14, verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقد'), ('bank', 'بانک'), ('mobile', 'موبایل پول'), ('saraf', 'صراف')], default='cash', max_length=20, verbose_name='روش پرداخت'),
        ),
        migrations.AlterField(
            model_name='suppliertransaction',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=16, verbose_name='مبلغ'),
        ),
    ]
