# Generated by Django 5.0.6 on 2026-06-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_supplier_advance_balance_usd_supplier_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='opening_balance_usd',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16, verbose_name='بدهی اولیه به تامین\u200cکننده (دالر)'),
        ),
    ]
