# Generated by Django 5.0.6 on 2026-06-26 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='loandakkhanentry',
            new_name='loans_dakka_entry_d_c85fac_idx',
            old_name='loans_dakkan_date_idx',
        ),
        migrations.RenameIndex(
            model_name='loandakkhanentry',
            new_name='loans_dakka_currenc_6502a9_idx',
            old_name='loans_dakkan_currency_idx',
        ),
        migrations.RenameIndex(
            model_name='loandakkhanentry',
            new_name='loans_dakka_is_outf_0b880c_idx',
            old_name='loans_dakkan_outflow_idx',
        ),
        migrations.RenameIndex(
            model_name='loanperson',
            new_name='loans_perso_name_170b28_idx',
            old_name='loans_perso_name_idx',
        ),
        migrations.RenameIndex(
            model_name='loanperson',
            new_name='loans_perso_is_acti_0b6c0d_idx',
            old_name='loans_perso_active_idx',
        ),
        migrations.RenameIndex(
            model_name='loantransaction',
            new_name='loans_trans_person__97d0c9_idx',
            old_name='loans_tx_person_date_idx',
        ),
        migrations.RenameIndex(
            model_name='loantransaction',
            new_name='loans_trans_tx_type_c73f2f_idx',
            old_name='loans_tx_type_idx',
        ),
        migrations.RenameIndex(
            model_name='loantransaction',
            new_name='loans_trans_currenc_3700bb_idx',
            old_name='loans_tx_currency_idx',
        ),
        migrations.RenameIndex(
            model_name='loantransaction',
            new_name='loans_trans_payment_b926f5_idx',
            old_name='loans_tx_method_idx',
        ),
        migrations.RenameIndex(
            model_name='loantransaction',
            new_name='loans_trans_is_reve_01aff3_idx',
            old_name='loans_tx_reversed_idx',
        ),
    ]
