# Generated by Django 5.0.6 on 2026-05-24 00:18

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('name', models.CharField(max_length=200, verbose_name='نام صراف')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('phone2', models.CharField(blank=True, max_length=20, verbose_name='تلفن دوم')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('balance_afn', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='مانده AFN')),
                ('balance_usd', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='مانده USD')),
            ],
            options={
                'verbose_name': 'صراف',
                'verbose_name_plural': 'صرافان',
                'db_table': 'banker_banker',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='banker_bank_name_234a63_idx'), models.Index(fields=['is_active'], name='banker_bank_is_acti_912d05_idx')],
            },
        ),
        migrations.CreateModel(
            name='BankerTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('tx_type', models.CharField(choices=[('given', 'پول داده شده به صراف'), ('received', 'پول دریافت شده از صراف')], max_length=20, verbose_name='نوع تراکنش')),
                ('currency', models.CharField(choices=[('AFN', 'افغانی'), ('USD', 'دالر')], default='AFN', max_length=5, verbose_name='ارز')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='مبلغ')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=12, verbose_name='نرخ تبدیل (۱ USD = ؟ AFN)')),
                ('amount_afn', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='معادل افغانی')),
                ('balance_after_afn', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='مانده AFN بعد از تراکنش')),
                ('balance_after_usd', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='مانده USD بعد از تراکنش')),
                ('transaction_date', models.DateField(verbose_name='تاریخ')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='مرجع')),
                ('banker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='banker.banker', verbose_name='صراف')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banker_transactions', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
            ],
            options={
                'verbose_name': 'تراکنش صراف',
                'verbose_name_plural': 'تراکنش\u200cهای صراف',
                'db_table': 'banker_transaction',
                'ordering': ['-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['banker', '-transaction_date'], name='banker_tran_banker__249780_idx'), models.Index(fields=['tx_type'], name='banker_tran_tx_type_4e2c53_idx'), models.Index(fields=['currency'], name='banker_tran_currenc_afd6e0_idx'), models.Index(fields=['-transaction_date'], name='banker_tran_transac_4400f6_idx')],
            },
        ),
    ]
