# Generated by Django 5.0.6 on 2026-06-19 17:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banker',
            name='balance_eur',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='مانده EUR'),
        ),
        migrations.AddField(
            model_name='banker',
            name='balance_irr',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='مانده IRR'),
        ),
        migrations.AddField(
            model_name='bankertransaction',
            name='balance_after_eur',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='مانده EUR بعد از تراکنش'),
        ),
        migrations.AddField(
            model_name='bankertransaction',
            name='balance_after_irr',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='مانده IRR بعد از تراکنش'),
        ),
        migrations.AlterField(
            model_name='bankertransaction',
            name='currency',
            field=models.CharField(choices=[('AFN', 'افغانی'), ('USD', 'دالر'), ('EUR', 'یورو'), ('IRR', 'تومان ایران')], default='AFN', max_length=5, verbose_name='ارز'),
        ),
        migrations.AlterField(
            model_name='bankertransaction',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=12, verbose_name='نرخ تبدیل (۱ واحد = ؟ AFN)'),
        ),
    ]
