# Generated by Django 5.0.6 on 2026-05-23 22:45

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='مقدار')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت خرید فی واحد')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='تخفیف %')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='مبلغ تخفیف')),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='مجموع ردیف')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا')),
            ],
            options={
                'verbose_name': 'ردیف خرید',
                'verbose_name_plural': 'ردیف\u200cهای خرید',
                'db_table': 'purchases_invoice_item',
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='شماره فاکتور')),
                ('purchase_date', models.DateField(verbose_name='تاریخ خرید')),
                ('supplier_invoice_number', models.CharField(blank=True, max_length=100, verbose_name='شماره فاکتور تامین\u200cکننده')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='جمع قبل از تخفیف')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='تخفیف')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='مبلغ کل')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='پرداخت شده')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='باقی\u200cمانده')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('unpaid', 'پرداخت نشده'), ('partial', 'پرداخت جزئی'), ('paid', 'پرداخت کامل'), ('returned', 'برگشت شده')], default='unpaid', max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases_created', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
            ],
            options={
                'verbose_name': 'فاکتور خرید',
                'verbose_name_plural': 'فاکتورهای خرید',
                'db_table': 'purchases_invoice',
                'ordering': ['-purchase_date', '-created_at'],
            },
        ),
    ]
