# Generated by Django 5.0.6 on 2026-05-23 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('purchases', '0001_initial'),
        ('suppliers', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='suppliers.supplier', verbose_name='تامین\u200cکننده'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='warehouse.warehouse', verbose_name='انبار'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_items', to='warehouse.stockbatch', verbose_name='بچ ایجاد شده'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchaseinvoice', verbose_name='فاکتور'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='inventory.product', verbose_name='محصول'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['invoice_number'], name='purchases_i_invoice_4b45d2_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['supplier', '-purchase_date'], name='purchases_i_supplie_305803_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['status'], name='purchases_i_status_123086_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['-purchase_date'], name='purchases_i_purchas_cdc188_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseitem',
            index=models.Index(fields=['invoice'], name='purchases_i_invoice_52e257_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseitem',
            index=models.Index(fields=['product'], name='purchases_i_product_15f21b_idx'),
        ),
    ]
