# Generated by Django 5.0.6 on 2026-06-14 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_purchaseinvoice_banker_purchaseinvoice_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='banker',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='payment_method',
        ),
    ]
