# Generated by Django 5.0.6 on 2026-06-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_purchaseinvoice_banker_purchaseinvoice_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقد'), ('saraf', 'صراف')], default='cash', max_length=20, verbose_name='روش پرداخت'),
        ),
    ]
