# Generated by Django 5.0.6 on 2026-05-23 22:52

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دسته\u200cبندی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی مصرف',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای مصارف',
                'db_table': 'expenses_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مصرف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='مبلغ (افغانی)')),
                ('expense_date', models.DateField(verbose_name='تاریخ مصرف')),
                ('payment_method', models.CharField(choices=[('cash', 'نقد'), ('bank', 'بانک'), ('mobile', 'موبایل پول')], default='cash', max_length=20, verbose_name='روش پرداخت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='approved', max_length=20, verbose_name='وضعیت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('receipt_number', models.CharField(blank=True, max_length=100, verbose_name='شماره رسید')),
                ('paid_to', models.CharField(blank=True, max_length=200, verbose_name='پرداخت به')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_approved', to=settings.AUTH_USER_MODEL, verbose_name='تایید\u200cکننده')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_created', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expenses.expensecategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'مصرف',
                'verbose_name_plural': 'مصارف',
                'db_table': 'expenses_expense',
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['-expense_date'], name='expenses_ex_expense_0d5c38_idx'), models.Index(fields=['category'], name='expenses_ex_categor_20264a_idx'), models.Index(fields=['status'], name='expenses_ex_status_cbb790_idx'), models.Index(fields=['payment_method'], name='expenses_ex_payment_20c388_idx')],
            },
        ),
    ]
