# Generated by Django 5.0.6 on 2026-06-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقد')], default='cash', max_length=20, verbose_name='روش پرداخت'),
        ),
    ]
