# Generated by Django 5.0.6 on 2026-06-17 20:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banker', '0001_initial'),
        ('expenses', '0002_alter_expense_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='amount_afn',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='معادل افغانی'),
        ),
        migrations.AddField(
            model_name='expense',
            name='banker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='banker.banker', verbose_name='صراف'),
        ),
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('AFN', 'افغانی ؋'), ('USD', 'دالر $')], default='AFN', max_length=3, verbose_name='واحد پول'),
        ),
        migrations.AddField(
            model_name='expense',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=12, verbose_name='نرخ تبدیل (۱ USD = ؟ AFN)'),
        ),
        migrations.AddField(
            model_name='expense',
            name='saraf_debt_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='بدهی به صراف'),
        ),
        migrations.AddField(
            model_name='expense',
            name='saraf_paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='مبلغ پرداخت شده به صراف'),
        ),
        migrations.AddField(
            model_name='expense',
            name='saraf_settled',
            field=models.BooleanField(default=False, verbose_name='تسویه شده با صراف'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقد'), ('saraf', 'صراف')], default='cash', max_length=20, verbose_name='روش پرداخت'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['banker'], name='expenses_ex_banker__f6b362_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['saraf_settled'], name='expenses_ex_saraf_s_31e9c4_idx'),
        ),
    ]
