# Generated by Django 5.0.6 on 2026-06-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_amount_afn_expense_banker_expense_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقد'), ('saraf', 'صراف'), ('dakkan', 'دخل دکان')], default='cash', max_length=20, verbose_name='روش پرداخت'),
        ),
    ]
